# Generated by Django 4.1.4 on 2023-03-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={},
        ),
    ]
