# Generated by Django 4.1.4 on 2023-03-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_home_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='button',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
