# Generated by Django 4.1.4 on 2023-03-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_home_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=25)),
                ('item_line', models.CharField(max_length=5)),
            ],
        ),
    ]
