# Generated by Django 4.1.4 on 2023-03-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
