# Generated by Django 4.1.4 on 2023-03-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_skills_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='title',
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(upload_to='home'),
        ),
    ]
