# Generated by Django 4.1.4 on 2023-03-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_skill_title_alter_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(default=1, upload_to='skill'),
            preserve_default=False,
        ),
    ]
