# Generated by Django 4.1.4 on 2023-03-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_skill_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.TextField()),
                ('list_desc', models.TextField()),
                ('list_desc_2', models.TextField()),
                ('button_text', models.CharField(max_length=20)),
                ('project_complated', models.CharField(max_length=20)),
                ('years_experience', models.CharField(max_length=20)),
                ('heppy_clients', models.CharField(max_length=20)),
                ('customer_reviews', models.CharField(max_length=20)),
            ],
        ),
    ]
