# Generated by Django 4.1.4 on 2023-03-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_abaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=300)),
                ('title', models.TextField()),
                ('type', models.CharField(max_length=300)),
                ('desc', models.TextField()),
            ],
        ),
    ]
