# Generated by Django 4.1.4 on 2023-03-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
                ('youtube', models.CharField(max_length=500)),
            ],
        ),
    ]
