# Generated by Django 4.1.4 on 2023-03-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='youtube',
            new_name='chrome',
        ),
    ]
