# Generated by Django 4.1.4 on 2023-03-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_youtube_work_chrome'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(default=1, upload_to='work'),
            preserve_default=False,
        ),
    ]
